blank_issue_enabled: true
contact_links:
  -Overview: General background needed for bounty hunter to complete task.
   Reference: An explanation as to where the bounty hunter should look or code that is affected.
   Acceptance Criteria: The criteria that needs to be completed in order for the bounty to be considered complete.
   Screenshots/Mockups (if applicable): screenshots related to UI changes for simple changes, links to clickable mockups for larger features
   Bounty Hunter: Information for bounty hunters to join ShapeShift discord and other general information (see below).